# Generated by Django 4.0.1 on 2022-01-08 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movieseries_options_movie_rating_movie_voters_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(check=models.Q(('value__range', (0, 5))), name='valid_value'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='rating_once'),
        ),
    ]
