# Generated by Django 4.0.1 on 2022-01-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_text_movieslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslist',
            name='title',
            field=models.CharField(choices=[('later', 'Watch Later'), ('viewed', 'Viewed'), ('abandoned', 'Abandoned')], max_length=100, unique=True),
        ),
    ]
