# Generated by Django 4.0.1 on 2022-01-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movieslist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieslist',
            name='description',
        ),
    ]
