# Generated by Django 4.0.1 on 2022-01-09 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_remove_movieslist_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abandoned', models.ManyToManyField(related_name='abandoned', to='movies.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed', models.ManyToManyField(related_name='viewed', to='movies.Movie')),
                ('watch_later', models.ManyToManyField(related_name='later', to='movies.Movie')),
            ],
        ),
    ]
