# Generated by Django 4.0.1 on 2022-01-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviesList',
        ),
    ]
