# Generated by Django 4.0.1 on 2022-01-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_profile_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
