# Generated by Django 4.0.1 on 2022-01-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='abandoned',
            field=models.ManyToManyField(blank=True, related_name='abandoned', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watch_later',
            field=models.ManyToManyField(blank=True, related_name='later', to='movies.Movie'),
        ),
    ]
