# Generated by Django 4.0.1 on 2022-01-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_avg_rate_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='valid_value',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='rating_once',
        ),
    ]
