# Generated by Django 4.0.1 on 2022-01-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_vote_valid_value_remove_vote_rating_once'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(check=models.Q(('value__range', (0, 5))), name='valid_value'),
        ),
    ]
